name: twisted_rl
channels:
  - pytorch
  - plotly
  - bottler
  - iopath
  - menpo
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - boltons=23.0.0=py39h06a4308_0
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.11.17=py39h06a4308_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - conda=23.7.2=py39hf3d152e_0
  - conda-package-handling=2.1.0=py39h06a4308_0
  - conda-package-streaming=0.8.0=py39h06a4308_0
  - contextlib2=21.6.0=pyhd8ed1ab_0
  - cryptography=39.0.1=py39h9ce1e76_0
  - cuda=11.6.1=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=12.1.105=0
  - cuda-libraries=11.6.1=0
  - cuda-libraries-dev=11.6.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.1.105=0
  - cuda-nsight-compute=12.1.1=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=12.1.105=0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=12.1.105=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=12.1.105=0
  - cuda-runtime=11.6.1=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=12.1.105=0
  - cuda-toolkit=11.6.1=0
  - cuda-tools=11.6.1=0
  - cuda-visual-tools=11.6.1=0
  - elfutils=0.189=hde5d1a3_0
  - expat=2.5.0=hcb278e6_1
  - freetype=2.12.1=h4a9f257_0
  - fvcore=0.1.5.post20221221=pyhd8ed1ab_0
  - gds-tools=1.6.1.9=0
  - geos=3.11.2=hcb278e6_0
  - giflib=5.2.1=h5eee18b_3
  - glew=2.1.0=h9c3ff4c_2
  - glfw3=3.2.1=0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - icu=58.2=he6710b0_3
  - idna=3.4=py39h06a4308_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - iopath=0.1.9=py39
  - ipykernel=6.28.0=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jupyter_client=8.6.0=py39h06a4308_0
  - jupyter_core=5.7.2=py39h06a4308_0
  - jupyterlab_widgets=3.0.10=py39h06a4308_0
  - krb5=1.19.4=h568e23c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libarchive=3.6.2=hb4bd9a0_1
  - libcublas=11.9.2.110=h5e84587_0
  - libcublas-dev=11.9.2.110=h5c901ab_0
  - libcufft=10.7.1.112=hf425ae0_0
  - libcufft-dev=10.7.1.112=ha5ce4c0_0
  - libcufile=1.6.1.9=0
  - libcufile-dev=1.6.1.9=0
  - libcurand=10.3.2.106=0
  - libcurand-dev=10.3.2.106=0
  - libcurl=7.88.1=h91b91d3_0
  - libcusolver=11.3.4.124=h33c3c4e_0
  - libcusparse=11.7.2.124=h7538f96_0
  - libcusparse-dev=11.7.2.124=hbbe9722_0
  - libdeflate=1.17=h5eee18b_0
  - libdrm=2.4.114=h166bdaf_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libglu=9.0.0=hf484d3e_1
  - libidn2=2.3.4=h5eee18b_0
  - libllvm16=16.0.0=hadd5161_1
  - libmicrohttpd=0.9.76=h5eee18b_0
  - libnghttp2=1.46.0=hce63b2e_0
  - libnpp=11.6.3.124=hd2722f0_0
  - libnpp-dev=11.6.3.124=h3c42840_0
  - libnvjpeg=11.6.2.124=hd473ad6_0
  - libnvjpeg-dev=11.6.2.124=hb5906b9_0
  - libpciaccess=0.17=h166bdaf_0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.13=h1bed415_1
  - libxml2=2.10.3=hcbfbd50_0
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mesa-libegl-cos6-x86_64=11.0.7=4
  - mesalib=23.0.1=h3855f93_0
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.6=py39h417a72b_1
  - mkl_random=1.2.2=py39h417a72b_1
  - mpi=1.0=openmpi
  - mpi4py=3.1.4=py39h3e5f7c9_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - nodejs=6.13.1=0
  - nsight-compute=2023.1.1.4=0
  - numpy-base=1.24.3=py39h060ed82_1
  - nvidiacub=1.10.0=0
  - openmpi=4.0.2=hb1b8bf9_1
  - openssl=1.1.1w=h7f8727e_0
  - packaging=23.0=py39h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py39h6a678d5_0
  - pip=23.1.2=pyhd8ed1ab_0
  - plotly=5.16.0=py_0
  - pluggy=1.0.0=py39h06a4308_1
  - portalocker=2.3.0=py39h06a4308_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycosat=0.6.4=py39h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py39h06a4308_1
  - pyopenssl=23.0.0=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.16=h7a1cb2a_0
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python_abi=3.9=2_cp39
  - pytorch-cuda=11.6=h867d48c_1
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0=py39hb9d737c_5
  - pyzmq=25.1.2=py39h6a678d5_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=pyhd8ed1ab_0
  - ruamel.yaml=0.17.21=py39h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py39h5eee18b_1
  - schema=0.7.5=pyhd8ed1ab_1
  - setuptools=67.8.0=py39h06a4308_0
  - shapely=2.0.1=py39hf1c3bca_1
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=8.2.2=py39h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.12.0=py39h06a4308_0
  - tornado=6.4.1=py39h5eee18b_0
  - tqdm=4.65.0=py39hb070fc8_0
  - typing_extensions=4.5.0=py39h06a4308_0
  - urllib3=1.26.16=py39h06a4308_0
  - wheel=0.38.4=py39h06a4308_0
  - xorg-damageproto=1.2.1=h7f98852_1002
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-glproto=1.4.17=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxdamage=1.1.5=h7f98852_1
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-randrproto=1.5.0=h7f98852_1001
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-util-macros=1.19.0=h27cfd23_2
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.4.2=h5eee18b_0
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h166bdaf_4
  - zstandard=0.19.0=py39h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==0.15.0
      - aiofile==3.8.7
      - aiofiles==23.1.0
      - aiohttp==3.8.4
      - aiohttp-cors==0.7.0
      - aiosignal==1.3.1
      - altair==5.3.0
      - antlr4-python3-runtime==4.9.3
      - anyio==3.7.0
      - appdirs==1.4.4
      - argcomplete==3.1.1
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - argparse==1.4.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - astunparse==1.6.3
      - async-lru==2.0.4
      - async-timeout==4.0.2
      - attrs==22.2.0
      - babel==2.12.1
      - bcrypt==4.2.1
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - blessed==1.20.0
      - blinker==1.8.2
      - boto3==1.28.28
      - botocore==1.31.28
      - box2d-py==2.3.5
      - bracex==2.3.post1
      - cachetools==5.3.0
      - caio==0.9.12
      - chart-studio==1.1.0
      - click==8.1.3
      - cloudpickle==1.3.0
      - cmake==3.26.4
      - cmx==0.0.31
      - colorful==0.5.5
      - comm==0.1.4
      - contourpy==1.0.7
      - croniter==1.3.15
      - cssutils==2.7.1
      - cycler==0.11.0
      - cython==0.29.33
      - dateutils==0.6.12
      - debugpy==1.6.8
      - decorator==4.4.2
      - deepdiff==6.3.0
      - defusedxml==0.7.1
      - df2img==0.2.11
      - dill==0.3.7
      - distlib==0.3.6
      - dm-control==1.0.14
      - dm-env==1.6
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - easydict==1.10
      - exceptiongroup==1.1.1
      - executing==1.2.0
      - expandvars==0.11.0
      - farama-notifications==0.0.4
      - fastapi==0.88.0
      - fasteners==0.18
      - fastjsonschema==2.18.0
      - ffmpeg==1.4
      - filelock==3.11.0
      - flatbuffers==1.12
      - fonttools==4.39.2
      - fqdn==1.5.1
      - frozenlist==1.3.3
      - fsspec==2023.5.0
      - functional-notations==0.5.2
      - future==0.18.3
      - gast==0.4.0
      - gensim==4.3.1
      - gitdb==4.0.10
      - gitpython==3.1.31
      - glfw==2.7.0
      - google-api-core==2.11.1
      - google-api-python-client==2.97.0
      - google-auth==2.16.2
      - google-auth-httplib2==0.1.0
      - google-auth-oauthlib==0.4.6
      - google-cloud-core==2.3.3
      - google-cloud-storage==2.10.0
      - google-crc32c==1.5.0
      - google-pasta==0.2.0
      - google-resumable-media==2.5.0
      - googleapis-common-protos==1.60.0
      - gpustat==1.1.1
      - grpcio==1.34.1
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==0.29.1
      - gymnasium-notices==0.0.1
      - gymnasium-robotics==1.2.4
      - h11==0.9.0
      - h5py==3.1.0
      - html2image==2.0.4.2
      - html5tagger==1.3.0
      - httpcore==0.11.1
      - httplib2==0.22.0
      - httptools==0.5.0
      - httpx==0.15.4
      - huggingface-hub==0.16.4
      - imageio==2.31.1
      - imageio-ffmpeg==0.4.8
      - importlib-metadata==6.1.0
      - importlib-resources==5.12.0
      - iniconfig==2.0.0
      - inquirer==3.1.3
      - instagrapi==1.17.10
      - ipython==8.14.0
      - ipywidgets==8.1.0
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jax-jumpy==1.0.0
      - jaynes==0.9.5
      - jedi==0.19.0
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.2.0
      - json5==0.9.14
      - jsonpickle==4.0.5
      - jsonschema==4.18.6
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.3.0
      - jupyter-core==5.3.1
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.24.0
      - jupyterlab-widgets==3.0.8
      - kaleido==0.2.1
      - keras==2.11.0
      - keras-nightly==2.5.0.dev2021032900
      - keras-preprocessing==1.1.2
      - killport==1.2.0
      - kiwisolver==1.4.4
      - labmaze==1.0.6
      - lazy-loader==0.3
      - libclang==15.0.6.1
      - lightning==2.0.3
      - lightning-cloud==0.5.36
      - lightning-utilities==0.8.0
      - lit==16.0.5.post0
      - llvmlite==0.39.1
      - lxml==4.9.2
      - lz4==4.3.2
      - markdown==3.4.1
      - markdown-it-py==2.2.0
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - mdurl==0.1.2
      - memory-profiler==0.61.0
      - mistune==3.0.1
      - ml-logger==0.10.21
      - more-itertools==10.1.0
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.0.5
      - mujoco==2.3.7
      - multidict==6.0.4
      - nbclient==0.8.0
      - nbconvert==7.7.3
      - nbformat==5.9.2
      - nest-asyncio==1.5.7
      - networkx==3.1
      - nltk==3.8.1
      - notebook==7.0.2
      - notebook-shim==0.2.3
      - num2words==0.5.12
      - numba==0.56.4
      - numpy==1.25.2
      - numpy-quaternion==2022.4.3
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.535.133
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencensus==0.11.3
      - opencensus-context==0.1.3
      - opencv-python==4.7.0.72
      - opt-einsum==3.3.0
      - ordered-set==4.1.0
      - overrides==7.3.1
      - pandas==2.0.3
      - pandocfilters==1.5.0
      - paramiko==3.5.1
      - params-proto==2.11.14
      - patchelf==0.17.2.1
      - pathtools==0.1.2
      - pettingzoo==1.24.3
      - platformdirs==3.2.0
      - proglog==0.1.10
      - prometheus-client==0.17.1
      - promise==2.3
      - prompt-toolkit==3.0.39
      - protobuf==5.27.2
      - psutil==5.9.4
      - py-spy==0.3.14
      - pyaml==23.5.9
      - pyarrow==12.0.1
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycryptodomex==3.17
      - pycurl==7.45.2
      - pydantic==1.10.7
      - pydeck==0.9.1
      - pygame==2.1.0
      - pyglet==1.5.0
      - pyjwt==2.7.0
      - pynacl==1.5.0
      - pyopengl==3.1.6
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - pytest==7.3.1
      - python-editor==1.0.4
      - python-json-logger==2.0.7
      - python-multipart==0.0.6
      - pytorch-lightning==2.0.3
      - pytz==2023.3
      - pyvis==0.3.2
      - pywavelets==1.4.1
      - ray==2.6.1
      - readchar==4.0.5
      - referencing==0.30.0
      - regex==2023.6.3
      - requests-futures==1.0.1
      - requests-oauthlib==1.3.1
      - requests-toolbelt==1.0.0
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986==1.5.0
      - rfc3986-validator==0.1.1
      - rich==13.4.1
      - rpds-py==0.9.2
      - rsa==4.9
      - s3transfer==0.6.2
      - safetensors==0.3.1
      - sanic==23.6.0
      - sanic-cors==2.2.0
      - sanic-routing==23.6.0
      - scikit-image==0.21.0
      - scikit-learn==1.2.2
      - scikit-video==1.1.11
      - scipy==1.10.1
      - scp==0.15.0
      - seaborn==0.12.2
      - send2trash==1.8.2
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - sentry-sdk==1.17.0
      - setproctitle==1.3.2
      - shapley==1.0.3
      - shortuuid==1.0.11
      - six==1.15.0
      - smart-open==6.3.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - stack-data==0.6.2
      - starlette==0.22.0
      - starsessions==1.3.0
      - streamlit==1.36.0
      - strenum==0.4.15
      - swig==4.1.1
      - sympy==1.12
      - termcolor==1.1.0
      - terminado==0.17.1
      - threadpoolctl==3.1.0
      - tifffile==2023.8.12
      - tinycss2==1.2.1
      - tokenizers==0.13.3
      - toml==0.10.2
      - tomli==2.0.1
      - torch==2.0.1
      - torch-geometric==2.3.1
      - torchmetrics==0.11.4
      - torchvision==0.15.2
      - tracerite==1.1.0
      - traitlets==5.9.0
      - transformers==4.31.0
      - trash-cli==0.23.2.13.2
      - triton==2.1.0
      - typing==3.7.4.3
      - tzdata==2023.3
      - ujson==5.7.0
      - uri-template==1.3.0
      - uritemplate==4.1.1
      - uvicorn==0.22.0
      - uvloop==0.17.0
      - virtualenv==20.21.0
      - wandb==0.17.4
      - watchdog==4.0.1
      - waterbear==2.6.7
      - wcmatch==8.4.1
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.2.3
      - websockets==11.0.3
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.8
      - wrapt==1.12.1
      - yarl==1.9.2
      - zipp==3.15.0
prefix: /home/g/guyfreund/miniconda3/envs/knot_tying_url_remote
